name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest playwright pytest-playwright pytest-html
        python -m playwright install
    - name: 🧪 Run tests with Allure
      run: |
        pytest --alluredir=reports/allure-results

    - name: 🧰 Install Allure commandline
      uses: addnab/docker-run-action@v3
      with:
        image: frankescobar/allure-docker-service
        options: -v ${{ github.workspace }}/reports:/app/allure-results
        run: |
          allure generate /app/allure-results -o /app/allure-report --clean

    - name: 💾 Upload Allure Report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-report

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/